### ISSUE TITLE
Failed to extract any useful SNPs

### ISSUE THREAD

**Issue by VekiJ** [funpopgen/veqtl-mapper#6]
Hello,

I have the following problem when running veqtl-mapper with my files: 

Failed to extract any useful SNPs for ENSG00000238009.2. Run: 
"tabix genotype.chr22.europe.veqtl_mapper.final.sorted.vcf.gz 1:0-1133566 | grep -v '#' | cut -f1,2,4,5,10-" (this happens for many regions)

I tried so many solutions to fix this problem and none of them helped me. Finally I tried to run FastQTL tool with these files and it works with this tool. From what I know veqtl-mapper should use the same files as FastQTL, with the exception that the bed file should be uncompressed.

This is the comand I run: veqtl-mapper --vcf genotype.chr22.europe.veqtl_mapper.final.vcf.gz --bed quantification.veqtl_mapper.final.bed --out result.txt

In this folder you can find the files I used:

https://drive.google.com/drive/folders/0B17M59VMwaKscHVOTG4tandxdk0

Could you please check the format of my files and tell me what I am doing wrong?

Thank you!!

**Comment by abrown25** [comment]
I think the problem is your genotype file has missing data, and any SNP with missing data we drop. FastQTL imputes "average genotype" at these observations, but that's not something I want to do, as it assumes certain properties for the missingness.

Looking at the IDs, this looks like 1000 Genomes data, I think the latest phase 3 version doesn't have any missing data. Otherwise, all I can really suggest is making a genotype file where individuals with completely missing data are removed.

Also, some rows in your vcf file have too many columns, because the polyphen annotation has been split into new columns (snp_22_16287851 for example).
